name: native_video_player
description: A Flutter widget to play videos on iOS and Android using a native implementation.
version: 1.2.0+3
repository: https://github.com/albemala/native_video_player

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.11
  path: ^1.8.1

  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  # linting
  very_good_analysis: ^3.1.0

flutter:
  plugin:
    platforms:
      android:
        package: me.albemala.native_video_player
        pluginClass: NativeVideoPlayerPlugin
      ios:
        pluginClass: NativeVideoPlayerPlugin
